# Generated by Django 3.2 on 2023-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.ManyToManyField(to='home.NewsletterUser'),
        ),
    ]
