# Generated by Django 3.2 on 2023-02-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designer',
            field=models.CharField(choices=[('Ela', 'Ela'), ('Lukasz', 'Lukasz')], default='Ela', max_length=10),
        ),
    ]
